name: Create Bio
description: Create your Blahaj.bio profile
title: "[Bio]: "
labels: ["bio-creation"]
body:
  - type: input
    id: username
    attributes:
      label: Username
      description: Your desired username (only letters, numbers, and hyphens) blahaj.io/@blahaj
      placeholder: "blahaj-lover"
    validations:
      required: true
  - type: input
    id: display_name
    attributes:
      label: Display Name
      description: Your display name | can be capital and have other symbols
      placeholder: "Blahaj Enthusiast"
    validations:
      required: true
  - type: input
    id: pronouns
    attributes:
      label: Pronouns
      description: Your pronouns | He/him | She/Her | They/Them | He/They | She/They | any/all | other/pronouns 
      placeholder: "They/Them"
    validations:
      required: true
  - type: textarea
    id: bio
    attributes:
      label: Bio
      description: Tell us about yourself
      placeholder: "I love Blahaj and coding!"
    validations:
      required: true
  - type: textarea
    id: links
    attributes:
      label: Website Links
      description: One link per line
      placeholder: |
        https://github.com/nobleskye/blahaj.bio
        https://nobleskye.dev
        https://bsky.app/profile/nobleskye.dev
    validations:
      required: false
  # - type: checkboxes
  #   id: terms
  #   attributes:
  #     label: Code of Conduct
  #     description: By submitting this, you agree to follow our [Code of Conduct](https://github.com/nobleskye/blahaj.bio/code_of_conduct.md). 
  #     options:
  #       - label: I agree to follow this project's Code of Conduct
  #         required: true 
 
