name: Generate Profile Page

on:
  issues:
    types:
      - opened

jobs:
  generate-profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract issue data
        id: extract
        run: |
          USERNAME=$(grep -A1 'id: username' "$GITHUB_EVENT_PATH" | tail -n1 | awk '{$1=$1};1')
          DISPLAY_NAME=$(grep -A1 'id: display_name' "$GITHUB_EVENT_PATH" | tail -n1 | awk '{$1=$1};1')
          BIO=$(awk '/id: bio/{flag=1; next} /id: links/{flag=0} flag' "$GITHUB_EVENT_PATH" | sed '/^$/d')
          LINKS=$(awk '/id: links/{flag=1; next} flag' "$GITHUB_EVENT_PATH" | sed '/^$/d')

          echo "USERNAME=${USERNAME}" >> $GITHUB_ENV
          echo "DISPLAY_NAME=${DISPLAY_NAME}" >> $GITHUB_ENV
          echo "BIO<<EOF" >> $GITHUB_ENV
          echo "${BIO}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "LINKS<<EOF" >> $GITHUB_ENV
          echo "${LINKS}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Generate profile page
        run: |
          mkdir -p profiles/${USERNAME}
          cat <<EOF > profiles/${USERNAME}/index.md
          ---
          layout: "profile"
          title: "${DISPLAY_NAME}'s Profile"
          ---

          # ${DISPLAY_NAME}

          ${BIO}

          ## Links
          ${LINKS}
          EOF

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add profiles/${USERNAME}/index.md
          git commit -m "Create profile page for ${USERNAME}" || echo "No changes to commit"
          git push

      - name: Close issue
        uses: peter-evans/close-issue@v2
        with:
          comment: "Profile page for [${USERNAME}](https://blahaj.bio/${USERNAME}) has been created!"
