name: "🐟 Profile Request"
description: "Request to add your profile to Blahaj.bio"
title: "Profile: [YOUR NAME]"
labels: ["profile"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit your profile! Please fill out the information below.
  
  - type: input
    id: name
    attributes:
      label: Name
      description: What name would you like displayed on your profile?
      placeholder: "Jane Doe"
    validations:
      required: true

  - type: input
    id: pronouns
    attributes:
      label: Pronouns
      description: What are your pronouns?
      placeholder: "they/them"
    validations:
      required: true

  - type: textarea
    id: bio
    attributes:
      label: Bio
      description: Tell us a bit about yourself! This will be displayed on your profile.
      placeholder: "I'm a software engineer who loves cats and coding!"
    validations:
      required: true

  - type: input
    id: website
    attributes:
      label: Website
      description: Do you have a personal website?
      placeholder: "https://example.com"
    validations:
      required: false

  - type: input
    id: github
    attributes:
      label: GitHub Username
      description: What's your GitHub username?
      placeholder: "@username"
    validations:
      required: true
      
  - type: input
    id: mastodon
    attributes:
      label: Mastodon
      description: What's your Mastodon handle?
      placeholder: "@username@instance.social"
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this profile, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow the Code of Conduct
          required: true
